name: Deploy to dev server

on: 
  push:
    branches:
      - dev

jobs:
  deploy:
  
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          ./build.sh

      - name: Save Docker image as .tar file
        run: |
          docker save bible-jot-client:latest -o bible-jot-client_latest.tar

      - name: Copy Docker image to the server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          source: "bible-jot-client_latest.tar"
          target: "~/bible-jot-client_latest.tar"
  
      - name: SSH to server and load Docker image
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          script: |
              docker load -i ~/bible-jot-client_latest.tar
              docker stop bible-jot-client || true
              docker rm bible-jot-client || true
              docker run -d --name bible-jot-client -p 80:80 bible-jot-client:latest